# Generated by Django 4.0.1 on 2022-02-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomm', '0002_image_delete_upload_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='photo',
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default='', upload_to='upload/product'),
            preserve_default=False,
        ),
    ]
