# Generated by Django 4.0.1 on 2022-02-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecomm', '0010_register_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_data',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
